on: [push]

name: Rust CI

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install geckodriver and start
        run: |
          sudo apt-get update
          sudo apt-get install firefox
          geckodriver &
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test

  check:
    name: Run cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
      - name: Run cargo check
        run: cargo check

  clippy:
    name: Run cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
      - name: Run cargo check
        run: cargo clippy
